name = "chickaree"
type = "webpack"
account_id = "75d4d63f3c7c3830efbe428bda49d72a"
zone_id = " "
route = "chickaree-web2.757live.workers.dev/*"

kv_namespaces = [
	 { binding = "RESOURCE_DOMAINS", preview_id = " ", id = " " }
]

[site]
bucket = "./node_modules/@chickaree/web/html"
entry-point = ""
