name = "chickaree"
type = "webpack"
account_id = "75d4d63f3c7c3830efbe428bda49d72a"
zone_id = " "
route = " "

kv_namespaces = [
	 { binding = "RESOURCE_DOMAINS", id = "46583e25fcdb4fd0bfc4394b320cd7e3" }
]

[site]
bucket = "./node_modules/@chickaree/web/html"
entry-point = ""
