name = "cdn-web"
type = "webpack"
account_id = "75d4d63f3c7c3830efbe428bda49d72a"
zone_id = " "
route = "cdn.757live.workers.dev/*"


[site]
bucket = "./node_modules/@chickaree/web/html"
entry-point = ""
